command:
  - "/bin/bash"
  - "-c"
  - |
    # Remove pnpm files
    rm -f pnpm-lock.yaml pnpm-workspace.yaml

    # Create database file
    touch nexus.db
    chmod 666 nexus.db

    # Build all apps
    npm run build --workspace=api --if-present 2>&1 | grep -v "Failed to patch lockfile" | grep -v "ENOWORKSPACES" || true
    npm run build --workspace=admin --if-present 2>&1 | grep -v "Failed to patch lockfile" | grep -v "ENOWORKSPACES" || true
    npm run build --workspace=web --if-present 2>&1 | grep -v "Failed to patch lockfile" | grep -v "ENOWORKSPACES" || true

    # Copy static assets to standalone (if they exist)
    [ -d "apps/api/.next/standalone" ] && cp -r apps/api/.next/static apps/api/.next/standalone/.next/ 2>/dev/null || true
    [ -d "apps/admin/.next/standalone" ] && cp -r apps/admin/.next/static apps/admin/.next/standalone/.next/ 2>/dev/null || true
    [ -d "apps/web/.next/standalone" ] && cp -r apps/web/.next/static apps/web/.next/standalone/.next/ 2>/dev/null || true

    # Start API
    if [ -f "apps/api/.next/standalone/server.js" ]; then
      cd apps/api/.next/standalone && PORT=3002 HOSTNAME=0.0.0.0 node server.js &
      cd ../../..
    else
      cd apps/api && PORT=3002 HOSTNAME=0.0.0.0 npm start -- -H 0.0.0.0 -p 3002 &
      cd ..
    fi

    # Start Admin
    if [ -f "apps/admin/.next/standalone/server.js" ]; then
      cd apps/admin/.next/standalone && PORT=3001 HOSTNAME=0.0.0.0 node server.js &
      cd ../../..
    else
      cd apps/admin && PORT=3001 HOSTNAME=0.0.0.0 npm start -- -H 0.0.0.0 -p 3001 &
      cd ..
    fi

    sleep 5

    # Start Web (foreground)
    if [ -f "apps/web/.next/standalone/server.js" ]; then
      cd apps/web/.next/standalone && PORT=8080 HOSTNAME=0.0.0.0 node server.js
    else
      cd apps/web && PORT=8080 HOSTNAME=0.0.0.0 npm start -- -H 0.0.0.0 -p 8080
    fi

env:
  - name: NODE_ENV
    value: "production"
  - name: NEXT_TELEMETRY_DISABLED
    value: "1"
