command:
  - "/bin/bash"
  - "-c"
  - |
    # Install dependencies
    npm install

    # Build web application (creates standalone output)
    npm run build --workspace=web

    # Copy static files and public assets to standalone directory
    cp -r apps/web/.next/static apps/web/.next/standalone/apps/web/.next/static
    if [ -d "apps/web/public" ]; then
      cp -r apps/web/public apps/web/.next/standalone/apps/web/public
    fi

    # Start standalone server
    cd apps/web/.next/standalone && node apps/web/server.js

env:
  - name: NODE_ENV
    value: "production"
  - name: PORT
    value: "8080"
  - name: HOSTNAME
    value: "0.0.0.0"
