command:
  - "/bin/bash"
  - "-c"
  - |
    # Create database file
    touch nexus.db
    chmod 666 nexus.db

    # Build all apps from root using workspace commands
    npm run build --workspace=api --if-present
    npm run build --workspace=admin --if-present
    npm run build --workspace=web --if-present

    # Start API in background
    npm run start --workspace=api -- -H 0.0.0.0 -p 3002 &

    # Start Admin in background
    npm run start --workspace=admin -- -H 0.0.0.0 -p 3001 &

    # Wait for services
    sleep 5

    # Start web app in foreground
    npm run start --workspace=web -- -H 0.0.0.0 -p 8080

env:
  - name: NODE_ENV
    value: "production"
  - name: PORT
    value: "8080"
  - name: HOSTNAME
    value: "0.0.0.0"
