command:
  - "/bin/bash"
  - "-c"
  - |
    # Install pnpm globally
    npm install -g pnpm@9.0.0

    # Install dependencies
    pnpm install

    # Create database file with proper permissions
    touch nexus.db
    chmod 666 nexus.db

    # Build all applications using turbo
    pnpm build

    # Start API in the background on port 3002
    cd apps/api && pnpm start -H 0.0.0.0 -p 3002 &
    API_PID=$!
    cd ../..

    # Start Admin in the background on port 3001
    cd apps/admin && pnpm start -H 0.0.0.0 -p 3001 &
    ADMIN_PID=$!
    cd ../..

    # Wait for background services to start
    sleep 5

    # Start web app in the foreground on port 8080
    cd apps/web && pnpm start -H 0.0.0.0 -p 8080

env:
  - name: NODE_ENV
    value: "production"
  - name: PORT
    value: "8080"
  - name: HOSTNAME
    value: "0.0.0.0"
