command:
  - "/bin/bash"
  - "-c"
  - |
    # Install dependencies
    npm install

    # Create database file with proper permissions
    touch nexus.db
    chmod 666 nexus.db

    # Build all applications
    npm run build --workspace=api
    npm run build --workspace=admin
    npm run build --workspace=web

    # Start API in the background on port 3002
    npm run start --workspace=api -- -H 0.0.0.0 -p 3002 &

    # Start Admin in the background on port 3001
    npm run start --workspace=admin -- -H 0.0.0.0 -p 3001 &

    # Wait for background services to start
    sleep 5

    # Start web app in the foreground on port 8080
    npm run start --workspace=web -- -H 0.0.0.0 -p 8080

env:
  - name: NODE_ENV
    value: "production"
  - name: PORT
    value: "8080"
  - name: HOSTNAME
    value: "0.0.0.0"
