command:
  - "/bin/bash"
  - "-c"
  - |
    # Install dependencies
    npm install

    # Build web application
    npm run build --workspace=web

    # Start web app on port 8080
    npm run start --workspace=web -- -H 0.0.0.0 -p 8080

env:
  - name: NODE_ENV
    value: "production"
  - name: PORT
    value: "8080"
  - name: HOSTNAME
    value: "0.0.0.0"
