command:
  - "/bin/bash"
  - "-c"
  - |
    # Remove pnpm files
    rm -f pnpm-lock.yaml pnpm-workspace.yaml

    # Create database file
    touch nexus.db
    chmod 666 nexus.db

    # Build apps (suppress lockfile warnings but check exit code)
    npm run build --workspace=api --if-present 2>&1 | grep -v "Failed to patch lockfile" | grep -v "ENOWORKSPACES" || true
    npm run build --workspace=admin --if-present 2>&1 | grep -v "Failed to patch lockfile" | grep -v "ENOWORKSPACES" || true
    npm run build --workspace=web --if-present 2>&1 | grep -v "Failed to patch lockfile" | grep -v "ENOWORKSPACES" || true

    # Verify builds succeeded
    if [ ! -d "apps/web/.next" ]; then
      echo "ERROR: Web app build failed"
      exit 1
    fi

    # Copy static files
    cp -r apps/api/.next/static apps/api/.next/standalone/apps/api/.next/ 2>/dev/null || true
    cp -r apps/admin/.next/static apps/admin/.next/standalone/apps/admin/.next/ 2>/dev/null || true
    cp -r apps/web/.next/static apps/web/.next/standalone/apps/web/.next/ 2>/dev/null || true

    # Start servers
    cd apps/api/.next/standalone && PORT=3002 HOSTNAME=0.0.0.0 node apps/api/server.js &
    cd ../../..

    cd apps/admin/.next/standalone && PORT=3001 HOSTNAME=0.0.0.0 node apps/admin/server.js &
    cd ../../..

    sleep 5

    cd apps/web/.next/standalone && PORT=8080 HOSTNAME=0.0.0.0 node apps/web/server.js

env:
  - name: NODE_ENV
    value: "production"
  - name: NEXT_TELEMETRY_DISABLED
    value: "1"
