command:
  - "/bin/bash"
  - "-c"
  - |
    # Create database file
    touch nexus.db
    chmod 666 nexus.db

    # Build apps individually
    cd apps/api && npm run build && cd ../..
    cd apps/admin && npm run build && cd ../..
    cd apps/web && npm run build && cd ../..

    # Start API in background
    cd apps/api && npm run start -- -H 0.0.0.0 -p 3002 &
    cd ../..

    # Start Admin in background
    cd apps/admin && npm run start -- -H 0.0.0.0 -p 3001 &
    cd ../..

    # Wait for services
    sleep 5

    # Start web app
    cd apps/web && npm run start -- -H 0.0.0.0 -p 8080

env:
  - name: NODE_ENV
    value: "production"
  - name: PORT
    value: "8080"
  - name: HOSTNAME
    value: "0.0.0.0"
