command:
  - "/bin/bash"
  - "-c"
  - |
    # Install dependencies (Databricks may have already done this)
    npm install

    # Build all applications using turbo directly
    ./node_modules/.bin/turbo run build

    # Start all applications using turbo directly
    ./node_modules/.bin/turbo run dev

env:
  - name: NODE_ENV
    value: "production"
  - name: PORT
    value: "8080"
