command:
  - "/bin/bash"
  - "-c"
  - |
    # Remove pnpm files
    rm -f pnpm-lock.yaml pnpm-workspace.yaml

    # Create database file
    touch nexus.db
    chmod 666 nexus.db

    # Build all apps (suppress lockfile warnings)
    npm run build --workspace=api --if-present 2>&1 | grep -v "Failed to patch lockfile" | grep -v "ENOWORKSPACES" || true
    npm run build --workspace=admin --if-present 2>&1 | grep -v "Failed to patch lockfile" | grep -v "ENOWORKSPACES" || true
    npm run build --workspace=web --if-present 2>&1 | grep -v "Failed to patch lockfile" | grep -v "ENOWORKSPACES" || true

    # Start all apps using next start
    npm run start --workspace=api -- -H 0.0.0.0 -p 3002 &
    npm run start --workspace=admin -- -H 0.0.0.0 -p 3001 &

    sleep 5

    # Start web in foreground
    npm run start --workspace=web -- -H 0.0.0.0 -p 8080

env:
  - name: NODE_ENV
    value: "production"
  - name: NEXT_TELEMETRY_DISABLED
    value: "1"
