command:
  - "/bin/bash"
  - "-c"
  - |
    # Install dependencies (Databricks may have already done this)
    npm install

    # Build all applications
    npm run build

    # Start all applications
    npm run dev

env:
  - name: NODE_ENV
    value: "production"
  - name: PORT
    value: "8080"
