command:
  - "/bin/bash"
  - "-c"
  - |
    # Install dependencies (Databricks may have already done this)
    npm install

    # Build and start the web application
    cd apps/web && npm run build && npm run start -- -H 0.0.0.0 -p 8080

env:
  - name: NODE_ENV
    value: "production"
  - name: PORT
    value: "8080"
  - name: HOSTNAME
    value: "0.0.0.0"
